/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import exceptions.DepartureDateException;
import exceptions.EmptySearchFieldException;
import exceptions.EntryDateException;
import exceptions.NotSelectedDatesException;
import java.util.Date;
import static java.util.Map.entry;
import javax.swing.JApplet;
import javax.swing.JOptionPane;
import model.Hotel;
import services.HotelService;
import services.ReservationService;

/**
 *
 * @author lugo
 */
public class AdminReports extends javax.swing.JPanel {

    Date today;
    HotelService hotelService;
    ReservationService reservationService;

    public AdminReports() {
        hotelService = new HotelService();
        reservationService = new ReservationService();
        today = new Date();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back_ground = new javax.swing.JPanel();
        search = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txt_searchHotel = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        btn_all_reports = new javax.swing.JButton();
        lbl_full_name = new javax.swing.JLabel();
        lbl_entry_date = new javax.swing.JLabel();
        calendar_entry_date = new com.toedter.calendar.JDateChooser();
        calendar_departure_date = new com.toedter.calendar.JDateChooser();
        lbl_entry_date1 = new javax.swing.JLabel();
        btn_search1 = new javax.swing.JButton();

        back_ground.setBackground(new java.awt.Color(255, 255, 255));

        search.setBackground(new java.awt.Color(166, 118, 163));

        jLabel10.setBackground(new java.awt.Color(54, 37, 89));
        jLabel10.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Reservation reports");

        javax.swing.GroupLayout searchLayout = new javax.swing.GroupLayout(search);
        search.setLayout(searchLayout);
        searchLayout.setHorizontalGroup(
            searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(583, Short.MAX_VALUE))
        );
        searchLayout.setVerticalGroup(
            searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(43, 43, 43))
        );

        txt_searchHotel.setBackground(new java.awt.Color(255, 255, 255));
        txt_searchHotel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txt_searchHotel.setName(""); // NOI18N

        btn_search.setBackground(new java.awt.Color(54, 37, 89));
        btn_search.setForeground(new java.awt.Color(255, 255, 255));
        btn_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/search-regular-24.png"))); // NOI18N
        btn_search.setText("Reports");
        btn_search.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        btn_all_reports.setBackground(new java.awt.Color(54, 37, 89));
        btn_all_reports.setForeground(new java.awt.Color(255, 255, 255));
        btn_all_reports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/plus-regular-24.png"))); // NOI18N
        btn_all_reports.setText("All reports");
        btn_all_reports.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_all_reports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_all_reportsActionPerformed(evt);
            }
        });

        lbl_full_name.setForeground(new java.awt.Color(153, 153, 153));
        lbl_full_name.setText("Hotel names:");

        lbl_entry_date.setForeground(new java.awt.Color(153, 153, 153));
        lbl_entry_date.setText("Entry date");

        lbl_entry_date1.setForeground(new java.awt.Color(153, 153, 153));
        lbl_entry_date1.setText("Departure date");

        btn_search1.setBackground(new java.awt.Color(54, 37, 89));
        btn_search1.setForeground(new java.awt.Color(255, 255, 255));
        btn_search1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/search-regular-24.png"))); // NOI18N
        btn_search1.setText("Reports");
        btn_search1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_search1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout back_groundLayout = new javax.swing.GroupLayout(back_ground);
        back_ground.setLayout(back_groundLayout);
        back_groundLayout.setHorizontalGroup(
            back_groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, back_groundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(back_groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_full_name)
                    .addComponent(txt_searchHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(398, 398, 398))
            .addGroup(back_groundLayout.createSequentialGroup()
                .addGroup(back_groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(back_groundLayout.createSequentialGroup()
                        .addGap(417, 417, 417)
                        .addComponent(btn_all_reports, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(back_groundLayout.createSequentialGroup()
                        .addGap(363, 363, 363)
                        .addGroup(back_groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_entry_date)
                            .addComponent(calendar_entry_date, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(back_groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calendar_departure_date, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_entry_date1))
                        .addGap(66, 66, 66)
                        .addGroup(back_groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_search)
                            .addComponent(btn_search1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        back_groundLayout.setVerticalGroup(
            back_groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(back_groundLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(lbl_full_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(back_groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(back_groundLayout.createSequentialGroup()
                        .addGroup(back_groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_searchHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(168, 168, 168)
                        .addGroup(back_groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(back_groundLayout.createSequentialGroup()
                                .addGroup(back_groundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_entry_date)
                                    .addComponent(lbl_entry_date1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(calendar_entry_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(calendar_departure_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn_search1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 245, Short.MAX_VALUE)
                .addComponent(btn_all_reports, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back_ground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back_ground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_all_reportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_all_reportsActionPerformed
        reservationService.generateReportPdfAllReservation();
    }//GEN-LAST:event_btn_all_reportsActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        try {
            reservationService.generateReportPdfReservation(txt_searchHotel.getText());

            txt_searchHotel.setText("");
        } catch (EmptySearchFieldException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_search1ActionPerformed

        try {
            Date entry = calendar_entry_date.getDate();
            Date departure = calendar_departure_date.getDate();
           

            if (departure.before(entry) || departure.toString().equals(entry.toString())) {
                throw new DepartureDateException();
            }if(entry == null || departure==null){
                throw new NotSelectedDatesException();
            }

            reservationService.createReportBetweenDates(entry, departure);

        } catch (EntryDateException | DepartureDateException | NotSelectedDatesException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }


    }//GEN-LAST:event_btn_search1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel back_ground;
    private javax.swing.JButton btn_all_reports;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_search1;
    private com.toedter.calendar.JDateChooser calendar_departure_date;
    private com.toedter.calendar.JDateChooser calendar_entry_date;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel lbl_entry_date;
    private javax.swing.JLabel lbl_entry_date1;
    private javax.swing.JLabel lbl_full_name;
    private javax.swing.JPanel search;
    private javax.swing.JTextField txt_searchHotel;
    // End of variables declaration//GEN-END:variables
}
