/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.BorderLayout;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import javax.swing.JPanel;
import model.Reservation;
import services.ReservationService;

/**
 *
 * @author lugo
 */
public class UserConfirmReservation extends javax.swing.JPanel {
    
    Reservation reservation;
    ReservationService reservationService;
    int typeRoom;

    public UserConfirmReservation(Reservation preReservation, int typeRoom) {
         initComponents();
        this.reservation = preReservation;
        
        reservationService = new ReservationService();
        
        this.typeRoom = typeRoom;
     
        initPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        search = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_full_name = new javax.swing.JTextField();
        lbl_full_name = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        lbl_entry_date = new javax.swing.JLabel();
        btn_confirm_reservation = new javax.swing.JButton();
        lbl_contact_number = new javax.swing.JLabel();
        txt_contact_number = new javax.swing.JTextField();
        lbl_hotel = new javax.swing.JLabel();
        txt_hotel = new javax.swing.JTextField();
        lbl_address = new javax.swing.JLabel();
        txt_address = new javax.swing.JTextField();
        calendar_entry_date = new com.toedter.calendar.JDateChooser();
        lbl_entry_date1 = new javax.swing.JLabel();
        calendar_departure_date = new com.toedter.calendar.JDateChooser();
        lbl_full_name1 = new javax.swing.JLabel();
        txt_number_room = new javax.swing.JTextField();
        lbl_full_name2 = new javax.swing.JLabel();
        txt_typeRoom = new javax.swing.JTextField();
        lbl_full_name3 = new javax.swing.JLabel();
        txt_total_price = new javax.swing.JTextField();
        txt_price_per_night1 = new javax.swing.JTextField();
        lbl_full_name4 = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1150, 1024));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(1140, 1024));

        search.setBackground(new java.awt.Color(166, 118, 163));

        jLabel11.setBackground(new java.awt.Color(54, 37, 89));
        jLabel11.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Reservation");

        javax.swing.GroupLayout searchLayout = new javax.swing.GroupLayout(search);
        search.setLayout(searchLayout);
        searchLayout.setHorizontalGroup(
            searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addGap(784, 784, 784))
        );
        searchLayout.setVerticalGroup(
            searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(33, 33, 33))
        );

        jLabel10.setBackground(new java.awt.Color(54, 37, 89));
        jLabel10.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Your reservation information");

        txt_full_name.setBackground(new java.awt.Color(255, 255, 255));
        txt_full_name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txt_full_name.setFocusable(false);
        txt_full_name.setName(""); // NOI18N
        txt_full_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_full_nameKeyTyped(evt);
            }
        });

        lbl_full_name.setForeground(new java.awt.Color(153, 153, 153));
        lbl_full_name.setText("Full name");

        lbl_email.setForeground(new java.awt.Color(153, 153, 153));
        lbl_email.setText("email");

        txt_email.setBackground(new java.awt.Color(255, 255, 255));
        txt_email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txt_email.setFocusable(false);
        txt_email.setName(""); // NOI18N
        txt_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_emailKeyTyped(evt);
            }
        });

        lbl_entry_date.setForeground(new java.awt.Color(153, 153, 153));
        lbl_entry_date.setText("Entry date");

        btn_confirm_reservation.setBackground(new java.awt.Color(54, 37, 89));
        btn_confirm_reservation.setForeground(new java.awt.Color(255, 255, 255));
        btn_confirm_reservation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/plus-regular-24.png"))); // NOI18N
        btn_confirm_reservation.setText("Confirm Resevation");
        btn_confirm_reservation.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_confirm_reservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirm_reservationActionPerformed(evt);
            }
        });

        lbl_contact_number.setForeground(new java.awt.Color(153, 153, 153));
        lbl_contact_number.setText("Contact number");

        txt_contact_number.setBackground(new java.awt.Color(255, 255, 255));
        txt_contact_number.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txt_contact_number.setFocusable(false);
        txt_contact_number.setName(""); // NOI18N
        txt_contact_number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_contact_numberKeyTyped(evt);
            }
        });

        lbl_hotel.setForeground(new java.awt.Color(153, 153, 153));
        lbl_hotel.setText("Hotel");

        txt_hotel.setBackground(new java.awt.Color(255, 255, 255));
        txt_hotel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txt_hotel.setFocusable(false);
        txt_hotel.setName(""); // NOI18N
        txt_hotel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_hotelKeyTyped(evt);
            }
        });

        lbl_address.setForeground(new java.awt.Color(153, 153, 153));
        lbl_address.setText("Address");

        txt_address.setBackground(new java.awt.Color(255, 255, 255));
        txt_address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txt_address.setFocusable(false);
        txt_address.setName(""); // NOI18N
        txt_address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_addressKeyTyped(evt);
            }
        });

        calendar_entry_date.setEnabled(false);
        calendar_entry_date.setFocusable(false);

        lbl_entry_date1.setForeground(new java.awt.Color(153, 153, 153));
        lbl_entry_date1.setText("Departure date");

        calendar_departure_date.setEnabled(false);
        calendar_departure_date.setFocusable(false);

        lbl_full_name1.setForeground(new java.awt.Color(153, 153, 153));
        lbl_full_name1.setText("Number room:");

        txt_number_room.setBackground(new java.awt.Color(255, 255, 255));
        txt_number_room.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txt_number_room.setFocusable(false);
        txt_number_room.setName(""); // NOI18N
        txt_number_room.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_number_roomKeyTyped(evt);
            }
        });

        lbl_full_name2.setForeground(new java.awt.Color(153, 153, 153));
        lbl_full_name2.setText("Number of guests:");

        txt_typeRoom.setBackground(new java.awt.Color(255, 255, 255));
        txt_typeRoom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txt_typeRoom.setFocusable(false);
        txt_typeRoom.setName(""); // NOI18N
        txt_typeRoom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_typeRoomKeyTyped(evt);
            }
        });

        lbl_full_name3.setForeground(new java.awt.Color(153, 153, 153));
        lbl_full_name3.setText("Total price:");

        txt_total_price.setBackground(new java.awt.Color(255, 255, 255));
        txt_total_price.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txt_total_price.setFocusable(false);
        txt_total_price.setName(""); // NOI18N
        txt_total_price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_total_priceKeyTyped(evt);
            }
        });

        txt_price_per_night1.setBackground(new java.awt.Color(255, 255, 255));
        txt_price_per_night1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txt_price_per_night1.setFocusable(false);
        txt_price_per_night1.setName(""); // NOI18N
        txt_price_per_night1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_price_per_night1KeyTyped(evt);
            }
        });

        lbl_full_name4.setForeground(new java.awt.Color(153, 153, 153));
        lbl_full_name4.setText("Price per night:");

        btn_back.setBackground(new java.awt.Color(54, 37, 89));
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/log-out-solid-24.png"))); // NOI18N
        btn_back.setText("Back");
        btn_back.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(lbl_full_name, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(477, 477, 477)
                        .addComponent(lbl_full_name1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(txt_full_name, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(181, 181, 181)
                        .addComponent(txt_number_room, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(lbl_email, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(506, 506, 506)
                        .addComponent(lbl_full_name2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(181, 181, 181)
                        .addComponent(txt_typeRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_contact_number, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_contact_number, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(181, 181, 181)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_full_name4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_price_per_night1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(lbl_hotel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(txt_hotel, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(lbl_address, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(670, 670, 670)
                        .addComponent(lbl_full_name3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(lbl_entry_date, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(199, 199, 199)
                        .addComponent(lbl_entry_date1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(btn_confirm_reservation, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(265, 265, 265)
                                .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(calendar_entry_date, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100)
                                .addComponent(calendar_departure_date, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(txt_total_price, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel10)
                .addGap(38, 38, 38)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_full_name)
                    .addComponent(lbl_full_name1))
                .addGap(2, 2, 2)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_full_name, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_number_room, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_email)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbl_full_name2)))
                .addGap(2, 2, 2)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_typeRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(lbl_contact_number)
                        .addGap(2, 2, 2)
                        .addComponent(txt_contact_number, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbl_full_name4)
                        .addGap(2, 2, 2)
                        .addComponent(txt_price_per_night1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addComponent(lbl_hotel)
                .addGap(12, 12, 12)
                .addComponent(txt_hotel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(lbl_address)
                .addGap(2, 2, 2)
                .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(lbl_full_name3)
                .addGap(2, 2, 2)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_entry_date)
                    .addComponent(lbl_entry_date1))
                .addGap(12, 12, 12)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calendar_entry_date, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calendar_departure_date, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_total_price, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_confirm_reservation, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 1211, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_full_nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_full_nameKeyTyped
        int key = evt.getKeyChar();
        //Validate if pressed key is a number, upper case, lower case or space
        boolean caracter = key >= 48 && key <= 57 || key >= 65 && key <= 90 || key >= 97 && key <= 122 || key == 32;
        //If is another thing do not put the character in the text field
        if (!caracter) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_full_nameKeyTyped

    private void txt_emailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emailKeyTyped
        int key = evt.getKeyChar();
        //Validate if pressed key is a number, upper case, lower case, space, "#", ",", "-", "." or "/"
        boolean caracter = key >= 48 && key <= 57 || key >= 65 && key <= 90 || key >= 97 && key <= 122 || key == 32 || key == 35 || key >= 44 && key <= 47;
        //If is another thing do not put the character in the text field
        if (!caracter) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_emailKeyTyped

    private void btn_confirm_reservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirm_reservationActionPerformed
        double totalPrice = Double.parseDouble(txt_total_price.getText());

        reservationService.insert(reservation.getUser().getId(), reservation.getHotel().getId(), reservation.getRoom().getId(), reservation.getEntryDate(), reservation.getDepartureDate(), 1, totalPrice);

        // preReservation = new Reservation(user, hotel, room, entry, departure,"pending" ,1);
        //ShowJPanel(new UserReserveRoom(preReservation,number_of_guests));

    }//GEN-LAST:event_btn_confirm_reservationActionPerformed

    private void txt_contact_numberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_contact_numberKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contact_numberKeyTyped

    private void txt_hotelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_hotelKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hotelKeyTyped

    private void txt_addressKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_addressKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_addressKeyTyped

    private void txt_number_roomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_number_roomKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_number_roomKeyTyped

    private void txt_typeRoomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_typeRoomKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_typeRoomKeyTyped

    private void txt_total_priceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_total_priceKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_total_priceKeyTyped

    private void txt_price_per_night1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_price_per_night1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_price_per_night1KeyTyped

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        ShowJPanel(new UserReserveRoom(reservation, typeRoom));
    }//GEN-LAST:event_btn_backActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_confirm_reservation;
    private com.toedter.calendar.JDateChooser calendar_departure_date;
    private com.toedter.calendar.JDateChooser calendar_entry_date;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel lbl_address;
    private javax.swing.JLabel lbl_contact_number;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_entry_date;
    private javax.swing.JLabel lbl_entry_date1;
    private javax.swing.JLabel lbl_full_name;
    private javax.swing.JLabel lbl_full_name1;
    private javax.swing.JLabel lbl_full_name2;
    private javax.swing.JLabel lbl_full_name3;
    private javax.swing.JLabel lbl_full_name4;
    private javax.swing.JLabel lbl_hotel;
    private javax.swing.JPanel search;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_contact_number;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_full_name;
    private javax.swing.JTextField txt_hotel;
    private javax.swing.JTextField txt_number_room;
    private javax.swing.JTextField txt_price_per_night1;
    private javax.swing.JTextField txt_total_price;
    private javax.swing.JTextField txt_typeRoom;
    // End of variables declaration//GEN-END:variables

    public void initPanel() {

       txt_total_price.setText(String.valueOf(reservationService.calculateTotalPrice(reservation.getRoom().getPricePerNight(), calculateTotalDays())));
        txt_number_room.setText(reservation.getRoom().getNumber());
        txt_typeRoom.setText(reservation.getRoom().getType());
        txt_price_per_night1.setText(String.valueOf(reservation.getRoom().getPricePerNight()));
        txt_full_name.setText(reservation.getUser().getUserName());
        txt_email.setText(reservation.getUser().getEmail());
        txt_contact_number.setText(reservation.getUser().getDetails());
        txt_hotel.setText(reservation.getHotel().getName());
        txt_address.setText(reservation.getHotel().getAddress());
      
       calendar_entry_date.setDate(reservation.getEntryDate());
       calendar_departure_date.setDate(reservation.getDepartureDate());
    }

    //this method calculate how many days there is between two dates
    public int calculateTotalDays() {
        Date entry = reservation.getEntryDate();
        Date departure = reservation.getDepartureDate();

        long millis = departure.getTime() - entry.getTime();

        int days = (int) TimeUnit.DAYS.convert(millis, TimeUnit.MILLISECONDS);

        return days;
    }
    
     private void ShowJPanel(JPanel panel) {
        panel.setSize(1140, 1024);
        panel.setLocation(0, 0);

        bg.removeAll();
        bg.add(panel, BorderLayout.CENTER);
        bg.revalidate();
        bg.repaint();
    }
}
